import { IconDownload, IconFileText, IconChartBar } from '@tabler/icons-react';
import React from 'react';

const Reports = () => {
  const reportTypes = [
    {
      title: 'User Analytics',
      description: 'Detailed user registration, activity, and retention metrics',
      icon: IconChartBar,
      lastGenerated: '2 hours ago',
      frequency: 'Daily'
    },
    {
      title: 'Revenue Report',
      description: 'Platform revenue, commissions, and financial overview',
      icon: IconFileText,
      lastGenerated: '5 hours ago',
      frequency: 'Daily'
    },
    {
      title: 'Transaction Report',
      description: 'All platform transactions and payment processing',
      icon: IconFileText,
      lastGenerated: '1 day ago',
      frequency: 'Weekly'
    },
    {
      title: 'Store Performance',
      description: 'Individual store metrics and seller analytics',
      icon: IconChartBar,
      lastGenerated: '1 day ago',
      frequency: 'Weekly'
    },
    {
      title: 'Support Metrics',
      description: 'Ticket resolution time, customer satisfaction scores',
      icon: IconFileText,
      lastGenerated: '3 days ago',
      frequency: 'Weekly'
    },
    {
      title: 'Platform Health',
      description: 'System uptime, error rates, and performance metrics',
      icon: IconChartBar,
      lastGenerated: '1 hour ago',
      frequency: 'Hourly'
    }
  ];

  const recentReports = [
    {
      id: 1,
      name: 'User Analytics - October 2025',
      type: 'User Analytics',
      generatedBy: 'System Auto',
      date: 'Oct 29, 2025',
      size: '2.4 MB'
    },
    {
      id: 2,
      name: 'Revenue Report - Week 43',
      type: 'Revenue',
      generatedBy: 'Alice Johnson',
      date: 'Oct 28, 2025',
      size: '1.8 MB'
    },
    {
      id: 3,
      name: 'Transaction Report - October 2025',
      type: 'Transactions',
      generatedBy: 'System Auto',
      date: 'Oct 27, 2025',
      size: '5.2 MB'
    }
  ];

  return (
    <div className="overview-container-ovr">
      <div className="store-welcome">
        <div>
          <h1 className="store-welcome-title">Reports & Analytics</h1>
          <span className="store-member-since">Generate and download platform reports</span>
        </div>
        <div className="store-actions">
          <button className="store-upload-btn admin-custom-report-btn">
            <IconFileText size={18} />
            <span>Generate Custom Report</span>
          </button>
        </div>
      </div>

      {/* Report Types Grid */}
      <div className="admin-reports-grid">
        {reportTypes.map((report, idx) => (
          <div key={idx} className="admin-report-card">
            <div className="admin-report-card-header">
              <div className="admin-report-icon">
                <report.icon size={24} />
              </div>
              <div className="admin-report-info">
                <h3 className="admin-report-title">{report.title}</h3>
                <p className="admin-report-desc">{report.description}</p>
              </div>
            </div>
            <div className="admin-report-meta">
              <span className="admin-report-meta-item">Last: {report.lastGenerated}</span>
              <span className="admin-report-meta-item">Frequency: {report.frequency}</span>
            </div>
            <button className="store-upload-btn admin-report-generate-btn">
              <IconDownload size={16} />
              <span>Generate Report</span>
            </button>
          </div>
        ))}
      </div>

      {/* Recent Reports */}
      <div className="store-orders-card">
        <div className="store-orders-header">
          <h2>Recent Reports</h2>
        </div>

        <div className="store-orders-table">
          <table>
            <thead>
              <tr>
                <th>S/N</th>
                <th>REPORT NAME</th>
                <th>TYPE</th>
                <th>GENERATED BY</th>
                <th>DATE</th>
                <th>FILE SIZE</th>
                <th>ACTIONS</th>
              </tr>
            </thead>
            <tbody>
              {recentReports.map((report, index) => (
                <tr key={report.id}>
                  <td data-label="S/N">{index + 1}</td>
                  <td data-label="Report Name">{report.name}</td>
                  <td data-label="Type">
                    <span className="admin-report-type-badge">
                      {report.type}
                    </span>
                  </td>
                  <td data-label="Generated By">{report.generatedBy}</td>
                  <td data-label="Date">{report.date}</td>
                  <td data-label="File Size">{report.size}</td>
                  <td data-label="Actions">
                    <button className="store-upload-btn admin-table-download-btn">
                      <IconDownload size={14} />
                      <span>Download</span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
